"""
OpenCastor Audit Log -- an append-only, hash-chained local record of events.

Records motor commands, approval decisions, config changes, errors,
and who/what triggered each event. The runtime only ever appends to it.

Each entry is hash-chained: the ``prev_hash`` field contains the SHA-256
digest of the previous entry's JSON line. The first entry uses
``prev_hash: "GENESIS"``. A broken link proves the file changed under the
chain; an intact chain proves only that whoever holds the file was
consistent, because the same process that writes a line can rewrite the
whole file and re-chain it. This is a local record the writing process
owns, and reading it here is never an outside party's check.

WHAT VERIFICATION CAN AND CANNOT SAY. :meth:`AuditLog.verify_chain_state`
returns three states, not two: ``no_log`` (nothing to check), ``ok``, and
``broken``. Until the 3.5 line a missing file returned "intact", so
``castor audit --verify`` in a directory with no log printed a clean bill
and exited 0. An entry with no ``prev_hash`` is now a BREAK as well; the
old code skipped it, which let an unchained tail append cleanly.

THE PATH IS ABSOLUTE AND RESOLVED ONCE. It used to be the cwd-relative
``.opencastor-audit.log``, so the log a service wrote depended on the
directory it happened to start in and the log the CLI read depended on the
directory you happened to stand in. See :func:`resolve_audit_path`.

Log format (one JSON object per line)::

    {"ts": "...", "event": "motor_command", "action": {...}, "source": "brain", "prev_hash": "..."}

Usage:
    castor audit                          # View recent audit entries
    castor audit --since 24h             # Filter by time
    castor audit --event motor_command   # Filter by event type
    castor audit --verify                # Verify hash chain integrity
"""

import contextlib
import hashlib
import json
import logging
import os
import threading
from datetime import datetime
from typing import TYPE_CHECKING, Any, Optional

if TYPE_CHECKING:
    from castor.quantum_commitment import CommitmentEngine  # noqa: F401

logger = logging.getLogger("OpenCastor.Audit")

#: The cwd-relative path this module used before 3.5. Kept only so that
#: :func:`orphaned_legacy_log` can tell an operator their old log is still
#: sitting where they last ran the runtime. Nothing reads or moves it.
LEGACY_AUDIT_FILE = ".opencastor-audit.log"

#: Verification states returned by :meth:`AuditLog.verify_chain_state`.
CHAIN_NO_LOG = "no_log"
CHAIN_OK = "ok"
CHAIN_BROKEN = "broken"


def resolve_audit_path() -> str:
    """Resolve the one absolute audit log path, from the robot home.

    Order:
      1. ``$OPENCASTOR_AUDIT_LOG`` (an explicit override, expanded)
      2. ``$ROBOT_HOME/audit.log`` (the variable every generated castor unit
         already sets, so this needs no new plumbing)
      3. ``~/.opencastor/audit.log``

    Resolved ONCE at import. The old value was a bare relative filename, so
    the runtime, the CLI and the POST_TOOL_USE hook each wrote a different
    file and none of them could see the others. The hook script generated by
    :mod:`castor.hooks.default_hooks` is rendered against this same value.
    """
    env_path = os.environ.get("OPENCASTOR_AUDIT_LOG")
    if env_path:
        return os.path.abspath(os.path.expanduser(env_path))
    robot_home = os.environ.get("ROBOT_HOME")
    if robot_home:
        return os.path.join(os.path.abspath(os.path.expanduser(robot_home)), "audit.log")
    return os.path.join(os.path.expanduser("~/.opencastor"), "audit.log")


#: The absolute audit log path, resolved once at import.
AUDIT_LOG_PATH = resolve_audit_path()

#: Back-compat alias. Now absolute.
_AUDIT_FILE = AUDIT_LOG_PATH


def orphaned_legacy_log(cwd: Optional[str] = None) -> Optional[str]:
    """Return the path of a cwd-relative pre-3.5 audit log, if one is here.

    The move to an absolute path orphans whatever the old relative path
    accumulated. We say so, once, in plain words. We do NOT move or merge it:
    an audit log that the tool silently relocates is an audit log the tool
    edited, and the next reader cannot tell a migration from a tamper.
    """
    candidate = os.path.join(cwd or os.getcwd(), LEGACY_AUDIT_FILE)
    if os.path.abspath(candidate) == os.path.abspath(AUDIT_LOG_PATH):
        return None
    return candidate if os.path.exists(candidate) else None


@contextlib.contextmanager
def _cross_process_lock(path: str):
    """Hold an advisory lock on ``<path>.lock`` for the duration of the block.

    The runtime and the generated POST_TOOL_USE hook now append to the SAME
    file, which is the whole point of resolving one absolute path. That makes
    the in-process :class:`threading.Lock` insufficient on its own: the hook is
    a separate bash process, and a read-last-line from one writer interleaved
    with an append from the other produces a ``prev_hash`` pointing at a line
    that is no longer last, i.e. a break the verifier would report as tampering
    when nothing was tampered with. ``audit_log.sh`` takes ``flock`` on exactly
    this file, so taking it here puts both writers in the same queue.

    Best effort by design: on a platform without ``fcntl``, or a filesystem
    that refuses the lock, the block still runs. A missed lock costs the same
    interleaving that existed before; failing the audit write instead would be
    worse.
    """
    lock_file = None
    try:
        import fcntl

        lock_file = open(path + ".lock", "a")
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
    except Exception as exc:  # pragma: no cover - platform dependent
        logger.debug("Audit cross-process lock unavailable (%s); continuing", exc)
        if lock_file is not None:
            lock_file.close()
            lock_file = None
    try:
        yield
    finally:
        if lock_file is not None:
            try:
                import fcntl

                fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)
            except Exception:  # pragma: no cover - platform dependent
                pass
            lock_file.close()


def _hash_entry(line: str) -> str:
    """Return the SHA-256 hex digest of *line* (stripped)."""
    return hashlib.sha256(line.strip().encode("utf-8")).hexdigest()


class AuditLog:
    """Append-only, hash-chained audit logger for significant robot events.

    Optionally enhanced with cryptographic commitment via QuantumLink-Sim.
    When a CommitmentEngine is attached, every audit entry is also sealed into
    a QKD-keyed (or hybrid) commitment chain, making tampering detectable even
    if the audit file itself is modified.

    Attach via::

        from castor.quantum_commitment import build_commitment_engine
        engine = build_commitment_engine(config)
        audit = get_audit()
        audit.attach_commitment_engine(engine)
    """

    def __init__(self, log_path: str = None):
        self._path = log_path or AUDIT_LOG_PATH
        # The default path is now absolute and lives in a directory that may
        # not exist yet. The append below swallows its own errors, so without
        # this the whole log would vanish quietly on a fresh robot.
        parent = os.path.dirname(self._path)
        if parent:
            try:
                os.makedirs(parent, exist_ok=True)
            except OSError as exc:
                logger.warning("Audit log directory %s not creatable: %s", parent, exc)
        self._lock = threading.Lock()
        self._commitment_engine: Optional[Any] = None  # CommitmentEngine | None
        self._watermark_index: dict[str, dict] = {}
        self._build_watermark_index()

    def _build_watermark_index(self) -> None:
        """Scan existing log file and populate _watermark_index from watermark_token fields."""
        if not os.path.exists(self._path):
            return
        try:
            with open(self._path) as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        entry = json.loads(line)
                        token = entry.get("watermark_token")
                        if token:
                            self._watermark_index[token] = entry
                    except (json.JSONDecodeError, TypeError):
                        continue
        except OSError:
            pass

    def attach_commitment_engine(self, engine: Optional[Any]) -> None:
        """Attach a CommitmentEngine for cryptographic audit sealing.

        Args:
            engine: A started CommitmentEngine, or None to disable.
        """
        self._commitment_engine = engine
        if engine is not None:
            logger.info(
                "Quantum commitment attached to AuditLog (mode=%s)",
                getattr(engine, "mode", "?"),
            )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _last_line(self) -> Optional[str]:
        """Return the last non-empty line of the log file, or *None*."""
        if not os.path.exists(self._path):
            return None
        last = None
        with open(self._path) as f:
            for line in f:
                stripped = line.strip()
                if stripped:
                    last = stripped
        return last

    # ------------------------------------------------------------------
    # Logging
    # ------------------------------------------------------------------

    def log(self, event: str, source: str = "system", **kwargs):
        """Append a hash-chained audit entry.

        Args:
            event: Event type (e.g. ``"motor_command"``, ``"approval_granted"``).
            source: What triggered this (e.g. ``"brain"``, ``"cli"``, ``"api"``).
            **kwargs: Additional event-specific data.
        """
        entry = {
            "ts": datetime.now().isoformat(),
            "event": event,
            "source": source,
        }
        entry.update(kwargs)

        with self._lock, _cross_process_lock(self._path):
            # Compute prev_hash from the last line in the log. Read and append
            # both happen inside the cross-process lock, because the hook is a
            # second writer on this same file.
            last = self._last_line()
            if last is None:
                entry["prev_hash"] = "GENESIS"
            else:
                entry["prev_hash"] = _hash_entry(last)

            # Cryptographic commitment (non-blocking; uses pre-generated pool key)
            if self._commitment_engine is not None:
                try:
                    commit_payload = {
                        "event": entry.get("event"),
                        "message_id": entry.get("message_id"),
                        "principal": entry.get("principal"),
                        "outcome": entry.get("outcome"),
                        "ai": entry.get("ai"),  # F5: model identity in commitment chain
                    }
                    record = self._commitment_engine.commit(commit_payload)
                    entry["commitment_id"] = record.id
                    entry["commitment_mode"] = record.key_mode
                    if record.qber is not None:
                        entry["commitment_qber"] = round(record.qber, 6)
                    entry["commitment_secure"] = record.key_secure
                except Exception as exc:
                    logger.warning("Commitment failed (non-fatal): %s", exc)

            try:
                with open(self._path, "a") as f:
                    f.write(json.dumps(entry, default=str) + "\n")
            except Exception as exc:
                logger.debug(f"Audit write failed: {exc}")

            # Update watermark index atomically with the write, using the fully-decorated
            # entry (includes ts, prev_hash, commitment_id, etc.).  Must happen inside
            # this lock block to avoid a race window between write and index update.
            wm_token = entry.get("watermark_token")
            if wm_token and hasattr(self, "_watermark_index"):
                self._watermark_index[wm_token] = entry

    # ------------------------------------------------------------------
    # Convenience loggers
    # ------------------------------------------------------------------

    def log_motor_command(
        self,
        action: dict,
        source: str = "brain",
        thought=None,
        watermark_token: str | None = None,
    ):
        """Log a motor command.

        Args:
            action: The action dict dispatched to the driver.
            source: Origin of the command (e.g. ``"brain"``).
            thought: Optional :class:`~castor.providers.base.Thought` that produced
                     the action.  When provided, an ``ai`` sub-dict is included in
                     the audit entry with model identity and confidence fields.
            watermark_token: Optional RCAN watermark token to embed in the log entry
                             and index for fast lookup.
        """
        kwargs = dict(
            action_type=action.get("type", "?"),
            linear=action.get("linear"),
            angular=action.get("angular"),
            intent_id=action.get("intent_id"),
        )
        if thought is not None:
            kwargs["ai"] = {
                "provider": getattr(thought, "provider", ""),
                "model": getattr(thought, "model", ""),
                "model_version": getattr(thought, "model_version", None),
                "layer": getattr(thought, "layer", "fast"),
                "confidence": getattr(thought, "confidence", None),
                "inference_latency_ms": getattr(thought, "latency_ms", None),
                "thought_id": getattr(thought, "id", None),
                "escalated": getattr(thought, "escalated", False),
            }
        if watermark_token is not None:
            kwargs["watermark_token"] = watermark_token
        self.log("motor_command", source=source, **kwargs)

    def log_approval(self, approval_id: int, decision: str, source: str = "cli"):
        """Log an approval decision."""
        self.log("approval", source=source, id=approval_id, decision=decision)

    def log_config_change(self, file: str, source: str = "wizard"):
        """Log a config file change."""
        self.log("config_changed", source=source, file=file)

    def log_error(self, message: str, source: str = "runtime"):
        """Log an error."""
        self.log("error", source=source, message=str(message)[:500])

    def log_startup(self, config_path: str):
        """Log a runtime startup."""
        self.log("startup", source="runtime", config=config_path)

    def log_shutdown(self, reason: str = "normal"):
        """Log a runtime shutdown."""
        self.log("shutdown", source="runtime", reason=reason)

    # ------------------------------------------------------------------
    # Chain verification
    # ------------------------------------------------------------------

    def verify_quantum_chain(self) -> tuple[bool, Optional[int]]:
        """Verify the cryptographic commitment chain (QuantumLink-Sim).

        Separate from ``verify_chain()`` which checks the SHA-256 hash chain
        in the audit log file.  This verifies the HMAC commitment chain held
        in-memory by the CommitmentEngine.

        Returns:
            ``(True, None)`` if intact or commitment is disabled.
            ``(False, idx)`` index of first broken commitment link.
        """
        if self._commitment_engine is None:
            return True, None
        return self._commitment_engine.verify_chain()

    def verify_chain(self, allow_unchained: bool = False) -> tuple[bool, Optional[int]]:
        """Boolean view of :meth:`verify_chain_state`.

        Returns:
            ``(True, None)`` if the chain is intact (or the file is empty).
            ``(False, index)`` where *index* is the first broken link.
            ``(False, None)`` when there is NO LOG FILE AT ALL. This used to
            return ``(True, None)``, i.e. "intact", which is the one answer a
            verifier must never give about a record it does not have. Callers
            that need to tell the two apart call :meth:`verify_chain_state`.
        """
        state, idx = self.verify_chain_state(allow_unchained=allow_unchained)
        return (state == CHAIN_OK, idx)

    def verify_chain_state(self, allow_unchained: bool = False) -> tuple[str, Optional[int]]:
        """Walk the log and verify every hash link.

        Args:
            allow_unchained: tolerate entries with no ``prev_hash`` field, the
                pre-chaining legacy format. OFF by default: an entry with no
                link is an entry nothing vouches for, and skipping it let a
                fabricated unchained tail verify clean.

        Returns:
            ``(CHAIN_NO_LOG, None)`` when the log file does not exist.
            ``(CHAIN_OK, None)`` when every link checks out (an existing but
            empty file counts as OK: it is a log, it just has no entries).
            ``(CHAIN_BROKEN, index)`` at the first bad or unlinked entry.
        """
        if not os.path.exists(self._path):
            return (CHAIN_NO_LOG, None)

        lines: list[str] = []
        with open(self._path) as f:
            for raw in f:
                stripped = raw.strip()
                if stripped:
                    lines.append(stripped)

        if not lines:
            return (CHAIN_OK, None)

        prev_line: Optional[str] = None
        chaining_started = False

        for idx, line in enumerate(lines):
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                return (CHAIN_BROKEN, idx)

            if "prev_hash" not in entry:
                # AN ENTRY WITH NO LINK IS A BREAK. The old code `continue`d
                # here and called the walk intact, so anyone could append a
                # tail of unchained lines and have the verifier bless it. The
                # legacy pre-chaining format is still readable, but only when
                # the caller says out loud that it wants that tolerance.
                if not allow_unchained:
                    return (CHAIN_BROKEN, idx)
                prev_line = line
                continue

            # This entry has prev_hash — chaining is active
            expected_prev = entry["prev_hash"]

            if not chaining_started and prev_line is None:
                # First entry overall — must be GENESIS
                if expected_prev != "GENESIS":
                    return (CHAIN_BROKEN, idx)
                chaining_started = True
                prev_line = line
                continue

            if not chaining_started and prev_line is not None:
                # First chained entry after legacy entries
                computed = _hash_entry(prev_line)
                if expected_prev != computed:
                    return (CHAIN_BROKEN, idx)
                chaining_started = True
                prev_line = line
                continue

            # Normal chained entry
            if prev_line is None:
                # Should not happen, but guard
                if expected_prev != "GENESIS":
                    return (CHAIN_BROKEN, idx)
            else:
                computed = _hash_entry(prev_line)
                if expected_prev != computed:
                    return (CHAIN_BROKEN, idx)

            prev_line = line

        return (CHAIN_OK, None)

    # ------------------------------------------------------------------
    # Reading
    # ------------------------------------------------------------------

    def read(self, since: str = None, event: str = None, limit: int = 50) -> list:
        """Read audit entries with optional filters.

        Args:
            since: Time window (e.g. ``"24h"``, ``"7d"``).
            event: Filter by event type.
            limit: Max entries to return.
        """
        if not os.path.exists(self._path):
            return []

        cutoff = None
        if since:
            from castor.memory_search import _parse_since

            cutoff = _parse_since(since)

        entries = []
        with open(self._path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue

                # Time filter
                if cutoff:
                    try:
                        entry_time = datetime.fromisoformat(entry["ts"])
                        if entry_time < cutoff:
                            continue
                    except Exception:
                        continue

                # Event filter
                if event and entry.get("event") != event:
                    continue

                entries.append(entry)

        # Return most recent entries
        return entries[-limit:]


# Global audit instance
_audit = AuditLog()


def get_audit() -> AuditLog:
    """Get the global audit log instance."""
    return _audit


def print_audit(entries: list):
    """Print audit entries."""
    try:
        from rich.console import Console
        from rich.table import Table

        console = Console()
        has_rich = True
    except ImportError:
        has_rich = False
        console = None

    if not entries:
        msg = "  No audit entries found."
        if has_rich:
            console.print(f"\n[dim]{msg}[/]\n")
        else:
            print(f"\n{msg}\n")
        return

    if has_rich:
        table = Table(title=f"Audit Log ({len(entries)} entries)", show_header=True)
        table.add_column("Time", style="dim", width=19)
        table.add_column("Event", style="bold")
        table.add_column("Source")
        table.add_column("Details")

        event_colors = {
            "motor_command": "cyan",
            "approval": "yellow",
            "config_changed": "blue",
            "error": "red",
            "startup": "green",
            "shutdown": "magenta",
        }

        for entry in entries:
            ts = entry.get("ts", "?")[:19]
            event = entry.get("event", "?")
            source = entry.get("source", "?")

            # Build details from remaining keys
            skip_keys = {"ts", "event", "source", "prev_hash"}
            details = ", ".join(
                f"{k}={v}" for k, v in entry.items() if k not in skip_keys and v is not None
            )

            color = event_colors.get(event, "white")
            table.add_row(ts, f"[{color}]{event}[/]", source, details[:60])

        console.print()
        console.print(table)
        console.print()
    else:
        print(f"\n  Audit Log ({len(entries)} entries):\n")
        for entry in entries:
            ts = entry.get("ts", "?")[:19]
            event = entry.get("event", "?")
            source = entry.get("source", "?")
            skip_keys = {"ts", "event", "source", "prev_hash"}
            details = ", ".join(
                f"{k}={v}" for k, v in entry.items() if k not in skip_keys and v is not None
            )
            print(f"  {ts}  {event:20s} [{source}] {details[:50]}")
        print()
