name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it. Feature requests from the community drive OpenCastor's roadmap.

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: A clear description of the feature.
      placeholder: "Add support for ROS2 as a driver protocol so I can use OpenCastor with my existing ROS2 setup."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New AI provider
        - New hardware driver
        - New messaging channel
        - CLI / developer experience
        - Dashboard / UI
        - Safety / reliability
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Why do you need this? What problem does it solve?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds?
    validations:
      required: false

  - type: dropdown
    id: willing_to_pr
    attributes:
      label: Would you be willing to submit a PR?
      options:
        - "Yes"
        - "Yes, with guidance"
        - "No"
    validations:
      required: false
