name: "🤖 New Recipe Submission"
description: Share a working robot config with the community
title: "recipe: "
labels: ["community-recipe", "submission"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your build! Please fill out the details below. A maintainer will help format it into a recipe.
        See [CONTRIBUTING-RECIPES.md](../../CONTRIBUTING-RECIPES.md) for full guidelines.

  - type: input
    id: name
    attributes:
      label: Recipe Name
      placeholder: "e.g., PiCar-X Home Patrol Bot"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What does it do?
      placeholder: "Describe your robot and what problem it solves. Be specific!"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Home & Indoor
        - Agriculture
        - Industrial
        - Education & Research
        - Outdoor & Exploration
        - Service & Companion
        - Other
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      options:
        - Beginner (kit-based, no soldering)
        - Intermediate (some wiring or custom parts)
        - Advanced (fleet, multiple sensors, custom builds)
    validations:
      required: true

  - type: input
    id: ai_provider
    attributes:
      label: AI Provider & Model
      placeholder: "e.g., Google Gemini 2.5 Flash"
    validations:
      required: true

  - type: textarea
    id: hardware
    attributes:
      label: Hardware List
      placeholder: |
        - Robot chassis (name, link)
        - Raspberry Pi model
        - Camera
        - Sensors
        - Approximate total cost
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: RCAN Config (paste your config.rcan.yaml)
      description: "Remove all API keys and personal info first!"
      render: yaml
    validations:
      required: true

  - type: textarea
    id: lessons
    attributes:
      label: What worked well? What would you change?
      placeholder: "Honest notes help others the most."
    validations:
      required: true

  - type: input
    id: budget
    attributes:
      label: Approximate Budget
      placeholder: "$120"

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I tested this on real hardware
          required: true
        - label: I removed all API keys and personal information
          required: true
        - label: I agree to license this recipe under Apache 2.0
          required: true
