apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencastor.fullname" . }}-secrets
  labels:
    {{- include "opencastor.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiToken: {{ .Values.secrets.apiToken | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  googleApiKey: {{ .Values.secrets.googleApiKey | quote }}
  openaiApiKey: {{ .Values.secrets.openaiApiKey | quote }}
  anthropicApiKey: {{ .Values.secrets.anthropicApiKey | quote }}
