"""
Default hook definitions for OpenCastor hardware safety gating.

Installs two shell scripts into ~/.opencastor/hooks/ on first use:
  - safety_check.sh  — denies motion commands when /tmp/robot-estop flag exists
  - audit_log.sh     — appends a hash-chained JSON audit line for every tool call

Both scripts carry a version marker on their second line. :func:`_ensure_script`
rewrites a script whose marker differs from the one this module ships, so a
robot that was brought up on an older release picks up a fixed script without
anyone hand-editing a file on the robot. A script with no marker at all is a
hand-written or pre-marker script and is left exactly where it is.
"""

from __future__ import annotations

import logging
from pathlib import Path

from castor.audit import AUDIT_LOG_PATH
from castor.hooks.runner import HookDefinition, HookEvent

logger = logging.getLogger("OpenCastor.DefaultHooks")

_HOOKS_DIR = Path.home() / ".opencastor" / "hooks"

#: Bump when either script below changes. The marker is what makes the
#: rewrite decidable; without it the installer could only ever write once.
HOOK_SCRIPT_VERSION = "2"

_MARKER_PREFIX = "# opencastor-hook-version:"

_SAFETY_CHECK_SCRIPT = f"""\
#!/usr/bin/env bash
{_MARKER_PREFIX} {HOOK_SCRIPT_VERSION}
# safety_check.sh — deny robot motion commands when e-stop flag is set
if [ -f /tmp/robot-estop ]; then
    echo "E-stop active: /tmp/robot-estop flag is set. Motion denied." >&2
    exit 1
fi
exit 0
"""

# THE HOOK WRITES INTO THE SAME FILE THE RUNTIME WRITES, AND CHAINS ITS LINE.
#
# Two separate defects used to live in these few lines. The log path was
# ${HOME}/.opencastor/audit.log while castor.audit wrote a cwd-relative
# .opencastor-audit.log, so the hook's record and the runtime's record were
# different files that never met. And the line was emitted with an `echo` of a
# double-quoted brace holding $INPUT unescaped, so any `$`, backtick or `$(...)`
# inside a tool argument was expanded by bash on its way to disk: the log
# could be made to say something the tool call never said, and a payload with
# an unbalanced quote broke the JSON outright.
#
# printf '%s' with the payload as an argument, never inside the format string.
# prev_hash is computed the way castor.audit._hash_entry computes it: SHA-256
# over the previous line, stripped. flock, when the host has it, keeps two
# concurrent tool calls from interleaving a read-then-append.
_AUDIT_LOG_SCRIPT = f"""\
#!/usr/bin/env bash
{_MARKER_PREFIX} {HOOK_SCRIPT_VERSION}
# audit_log.sh — append one hash-chained JSON audit entry per tool call.
# Generated by castor.hooks.default_hooks. Do not hand-edit: `castor up` and
# the runtime rewrite this file whenever the version marker above changes.
set -u
AUDIT_LOG="${{OPENCASTOR_AUDIT_LOG:-{AUDIT_LOG_PATH}}}"
mkdir -p "$(dirname "$AUDIT_LOG")"

_sha256() {{
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum | cut -d' ' -f1
    else
        shasum -a 256 | cut -d' ' -f1
    fi
}}

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
INPUT=$(cat)
[ -n "$INPUT" ] || INPUT='null'

if command -v flock >/dev/null 2>&1; then
    exec 9>>"$AUDIT_LOG.lock"
    flock 9
fi

PREV=$(tail -n 1 "$AUDIT_LOG" 2>/dev/null || true)
if [ -n "$PREV" ]; then
    PREV_HASH=$(printf '%s' "$PREV" | _sha256)
else
    PREV_HASH="GENESIS"
fi

printf '{{"ts":"%s","event":"tool_use","source":"hook","prev_hash":"%s","payload":%s}}\\n' \\
    "$TS" "$PREV_HASH" "$INPUT" >> "$AUDIT_LOG"
exit 0
"""

_MOTION_TOOLS = [
    "robot_navigate",
    "robot_drive",
    "send_command",
    "robot_move",
]


def _script_version(text: str) -> str | None:
    """Return the version marker of an installed script, or None if unmarked."""
    for line in text.splitlines()[:5]:
        stripped = line.strip()
        if stripped.startswith(_MARKER_PREFIX):
            return stripped[len(_MARKER_PREFIX) :].strip()
    return None


def _ensure_script(name: str, content: str) -> str:
    """Write the script if absent, or rewrite it when its marker is stale.

    Returns the path. A script that carries no marker is assumed to be an
    operator's own and is left alone: the rewrite exists to ship a fix, not
    to overwrite somebody's edit.
    """
    _HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    path = _HOOKS_DIR / name
    if path.exists():
        try:
            existing = path.read_text()
        except OSError as exc:
            logger.warning("Could not read hook script %s: %s", path, exc)
            return str(path)
        installed = _script_version(existing)
        if installed is None:
            logger.debug("Hook script %s has no version marker; leaving it alone", path)
            return str(path)
        if installed == HOOK_SCRIPT_VERSION:
            return str(path)
        path.write_text(content)
        path.chmod(0o755)
        logger.info(
            "Rewrote hook script %s (version %s -> %s)", path, installed, HOOK_SCRIPT_VERSION
        )
        return str(path)
    path.write_text(content)
    path.chmod(0o755)
    logger.info("Installed default hook script: %s", path)
    return str(path)


def get_default_hooks() -> list[HookDefinition]:
    """Return the default set of hook definitions, installing scripts as needed."""
    safety_script = _ensure_script("safety_check.sh", _SAFETY_CHECK_SCRIPT)
    audit_script = _ensure_script("audit_log.sh", _AUDIT_LOG_SCRIPT)

    return [
        HookDefinition(
            tools=_MOTION_TOOLS,
            script=safety_script,
            event=HookEvent.PRE_TOOL_USE,
            timeout_s=5.0,
        ),
        HookDefinition(
            tools=["*"],
            script=audit_script,
            event=HookEvent.POST_TOOL_USE,
            timeout_s=5.0,
        ),
    ]
