import base64
import logging
import os

from .base import BaseProvider, Thought

logger = logging.getLogger("OpenCastor.Anthropic")


class AnthropicProvider(BaseProvider):
    """Anthropic Claude adapter. Optimized for complex reasoning and safety."""

    # Default to the latest Claude model when none specified in config
    DEFAULT_MODEL = "claude-opus-4-6"

    # Claude setup-token prefix (generated by `claude setup-token`)
    SETUP_TOKEN_PREFIX = "sk-ant-oat01-"

    def __init__(self, config):
        # Apply default model before super().__init__ reads it
        if not config.get("model") or config.get("model") == "default-model":
            config["model"] = self.DEFAULT_MODEL
        super().__init__(config)
        import anthropic

        # Resolution order:
        # 1. ANTHROPIC_API_KEY env var (works for both API keys and setup-tokens)
        # 2. config api_key
        # 3. Claude CLI credentials (~/.claude/.credentials.json setup-token)
        api_key = os.getenv("ANTHROPIC_API_KEY") or config.get("api_key")

        if not api_key:
            # Try reading setup-token from Claude CLI credentials
            api_key = self._read_claude_setup_token()

        if not api_key:
            raise ValueError(
                "No Anthropic credentials found. Options:\n"
                "  1. Run 'claude setup-token' and set ANTHROPIC_API_KEY to the token\n"
                "     (uses your Claude Max/Pro subscription — no per-token billing)\n"
                "  2. Set ANTHROPIC_API_KEY to an API key from console.anthropic.com\n"
                "  3. Run 'castor wizard' to configure interactively"
            )

        if api_key.startswith(self.SETUP_TOKEN_PREFIX):
            logger.info("Using Claude setup-token (subscription auth)")
        else:
            logger.info("Using Anthropic API key")

        self.client = anthropic.Anthropic(api_key=api_key)

    @classmethod
    def _read_claude_setup_token(cls):
        """Read setup-token from Claude CLI credentials file.

        The Claude CLI stores credentials at ~/.claude/.credentials.json.
        A setup-token (sk-ant-oat01-...) works directly as an API key,
        allowing use of a Claude Max/Pro subscription without pay-per-token billing.
        """
        import json

        creds_path = os.path.expanduser("~/.claude/.credentials.json")
        try:
            if os.path.exists(creds_path):
                with open(creds_path) as f:
                    data = json.load(f)
                # Try setup-token first (preferred)
                oauth = data.get("claudeAiOauth", {})
                token = oauth.get("accessToken")
                if token and token.startswith(cls.SETUP_TOKEN_PREFIX):
                    logger.debug("Read setup-token from Claude CLI credentials")
                    return token
                # Also check for any token that looks like a setup-token
                if token and len(token) >= 80:
                    logger.debug("Read token from Claude CLI credentials")
                    return token
        except Exception as e:
            logger.debug(f"Could not read Claude credentials: {e}")
        return None

    def think(self, image_bytes: bytes, instruction: str) -> Thought:
        b64_image = base64.b64encode(image_bytes).decode("utf-8")

        # Build message content -- include image only if it has real data
        content = []
        is_blank = image_bytes == b"\x00" * len(image_bytes)
        if not is_blank and len(image_bytes) > 100:
            content.append(
                {
                    "type": "image",
                    "source": {
                        "type": "base64",
                        "media_type": "image/jpeg",
                        "data": b64_image,
                    },
                }
            )
        content.append({"type": "text", "text": instruction})

        try:
            response = self.client.messages.create(
                model=self.model_name,
                max_tokens=1024,
                system=self.system_prompt,
                messages=[{"role": "user", "content": content}],
            )
            text = response.content[0].text
            action = self._clean_json(text)
            return Thought(text, action)
        except Exception as e:
            logger.error(f"Anthropic error: {e}")
            return Thought(f"Error: {e}", None)
