[server]
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#0ea5e9"
backgroundColor = "#0a0b1e"
secondaryBackgroundColor = "#12142b"
textColor = "#e8e8ef"
font = "sans serif"
